#!/bin/bash
###############
# Help        #
###############
Help()
{
    #Display help
    echo "-m MOD_ID (Required)"
    echo "-l Location of server directory (Required)"

}

echo "MOD Downloader by ZURSK19";
modId=''
location=''
helpTerminate=false

while getops "m:l:h" flag; do
    case "${flag}" in
        h) helpTerminate=true;;
        m) modId="${OPTARG}";;
        l) location="${OPTARG}";;
    esac
done

if $helpTerminate; then
    echo "-m MOD_ID -l Location of server directory"
else
    if $modId=''; then
        echo "-m MOD_ID missing"
        exit 1
    fi
    if $location=''; then
        echo "-l location missing"
        exit 1
    fi
fi

echo "MOD ID: ${modId}";
echo "MOD ID: ${location}";