#!/bin/bash
###############
# Help        #
###############
Help()
{
    #Display help
    echo 
    echo "   Options:"
    echo "      -m MOD_ID (Required)"
    echo "      -l Location of server directory (Required)"
    echo
    exit 1

}

echo
echo "MOD Downloader by ZURSK19";
modId=''
location=''
helpTerminate=false

while getopts "m:l:h" opts; do
    echo "$opts"
    case "$opts" in
        h) Help;;
        m) modId="$OPTARG";;
        l) location="$OPTARG";;
    esac
done

if modId=''; then
    echo "-m MOD_ID missing"
    exit 1
fi
if location=''; then
    echo "-l location missing"
    exit 1
fi

echo "MOD ID: ${modId}";
echo "MOD ID: ${location}";