#!/bin/bash
###############
# Help        #
###############
Help()
{
    #Display help
    echo "-m MOD_ID (Required)"
    echo "-l Location of server directory (Required)"

}

echo "MOD Downloader by ZURSK19";
modId=''
location=''
helpTerminate=false

while getops "m:l:h" flag; do
    case "$flag" in
        h) Help;;
        m) modId="${OPTARG}";;
        l) location="${OPTARG}";;
    esac
done

if modId=''; then
    echo "-m MOD_ID missing"
    exit 1
fi
if location=''; then
    echo "-l location missing"
    exit 1
fi

echo "MOD ID: ${modId}";
echo "MOD ID: ${location}";